add dependency
ca-risken/code pull request #129
Opened 2022-08-24 08:12 UTC by iiiidaaa

Dependencyデータソースを追加します
スキャンの流れは以下の通りです。
- Queueからメッセージを取得
- メッセージ内のGitHubSettingIDからスキャン対象のGitHubSetting,DependencySettingを取得
- GitHubSettingよりターゲットの決定(Org/User,ターゲットリソース)
- ターゲットのリポジトリ一覧を取得
- リポジトリ一覧からスキャン対象外を選定(Fork,空のリポジトリ,サイズの大きいリポジトリ)
- スキャン対象ごとにtrivyの実行、Finding,Tag,Recommendの登録
- DependencySettingのステータスを更新しスキャン完了

Finding
- パッケージごとに脆弱性をまとめます
- スコアはTrivyから取得したSeverityを使用して、そのパッケージに紐づいている脆弱性で一番高いものに合わせます

スキャン対象外の選定についてはIssueを作成し、gitleaks合わせてどのような形にするかを相談する
- Fork repository
- サイズの大きいリポジトリ

2022-08-24 09:01 UTC, hnts commented on src/dependency/dependency.go
> +	bytes, err := ioutil.ReadFile(fileName)
ioutilはdeprecatedなのでos.ReadFileなどを使った方がよさそうです

2022-08-24 09:07 UTC, hnts commented on src/dependency/sqs.go
> +package main
このファイルもgitleaksと重複してそうです

2022-08-24 09:09 UTC, hnts commented on src/dependency/finding.go
> +func makeFindings(msg *message.CodeQueueMessage, report *trivytypes.Report) ([]*finding.FindingBatchForUpsert, error) {
こちらのfunctionもテストの記述お願いします

2022-08-24 09:09 UTC, hnts commented on src/dependency/finding.go
> +func getScore(vulnerabilities []trivytypes.DetectedVulnerability) float32 {
こちらもテストお願いします

2022-08-24 11:36 UTC, mmmknt requested changes

2022-08-24 11:36 UTC, mmmknt commented on src/dependency/handler.go
> +	gitHubSetting.PersonalAccessToken = token // Set the plaintext so that the value is still decipherable next processes.
ここで`gitHubSetting.PersonalAccessToken`を差し替えるなら、s.getGitHubSetting()の中でdecryptまでやってしまった方が見通しが良くなると思います。

2022-08-24 11:36 UTC, mmmknt commented on src/dependency/handler.go
> +	if repo == nil {
repoがnilになるのはどんなケースを想定していますか？エラーになるのがこの条件の時だけなので、不要なら戻り値からerrorを消してシンプルにできそうです。
また、この関数はscanをskipするかどうかの判定しか担っていないので、nilチェックが必要なら呼び出し元でやることにして、この関数ではskipする実装にしても良さそうです。

2022-08-24 11:36 UTC, mmmknt commented on src/dependency/handler.go
> +func (s *sqsHandler) listEnterpriseOrg(ctx context.Context, config *code.GitHubSetting) (*code.ListGitHubEnterpriseOrgResponse, error) {
このメソッドの中絵`s.codeClient.PutGitHubEnterpriseOrg()`と`s.codeClient.DeleteGitHubEnterpriseOrg()`を呼んでいるのって何をしているのでしょうか？

2022-08-24 12:03 UTC, iiiidaaa commented on src/dependency/grpc_client.go
> +package main
このファイルの以下の関数はcode以外のネームスペースでも同様の処理をしてます。
https://github.com/ca-risken/code/blob/e957feaa375d3b0126137696e8e7e70e16f36663/src/dependency/grpc_client.go#L14
https://github.com/ca-risken/code/blob/e957feaa375d3b0126137696e8e7e70e16f36663/src/dependency/grpc_client.go#L23
https://github.com/ca-risken/code/blob/e957feaa375d3b0126137696e8e7e70e16f36663/src/dependency/grpc_client.go#L41

なので、共通化するならば全てのデータソースに適応できる形にすべきだと考えましたがいかがでしょうか？
https://github.com/ca-risken/core/tree/master/proto か
https://github.com/ca-risken/common/tree/master/pkg/grpc_client
あたりにそれぞれのnewClientを置いて、それを各データソースが呼び出すような形をイメージしてます。
(この場合、共通のnewClientを呼び出すようにそれぞれを修正していく必要あり。issueに切ります)

こちらはCodeのデータソースのみで共通して使用されるものですね。
AWS,Googleなどネームスペースごとに共通のnew~~Clientを使用してる認識です。
https://github.com/ca-risken/code/blob/e957feaa375d3b0126137696e8e7e70e16f36663/src/dependency/grpc_client.go#L32

こちらもnewAWSClient,newCodeClientみたいなものを一括で記述してそれを呼び出す形にするのはどうでしょう？
https://github.com/ca-risken/common/tree/master/pkg/grpc_client か
https://github.com/ca-risken/datasource-api/tree/master/proto ここあたり？
(この場合もそれぞれのデータソースに修正をしていく必要あり)

gitleaksとdependencyのみで共通化という方針だと、実装イメージが思いつかないので教えて(相談させて)欲しいです。

2022-08-24 12:10 UTC, iiiidaaa commented on src/dependency/sqs.go
> +package main
このファイル内の関数もclientの方と同様にcode以外のネームスペースでも同様の処理をしてます。
なので、gitleaksとの共通化というよりはデータソースでの共通化という方針でいかがでしょうか？
https://github.com/ca-risken/go-sqs-poller/blob/master/worker/v5/util.go
あたりに、SQSConfigとnewSQSConsumerを用意する。
(この場合、ここに用意したSQSConfig,newSQSConsumerを使用するように各データソースを修正していく必要あり。issueに切ります)

その他の方法やgitleaksとdependencyのみで共通化という方針だと実装イメージが思いつかないので教えて(相談させて)欲しいです。

2022-08-24 12:50 UTC, iiiidaaa commented on src/dependency/Dockerfile
> +FROM public.ecr.aws/risken/code/dependency-base:v0.31.2
dependency-baseのバージョンがtrivyのバージョンになっちゃってます。。
別PRでcodebuildの修正を行なった後に、Dockerfile内のイメージバージョン修正します。
https://github.com/ca-risken/code/blob/master/codebuild/dependency-base-image/buildspec-batch.yml#L13 などを修正予定

2022-08-24 12:57 UTC, iiiidaaa commented on src/dependency/handler.go
> +func (s *sqsHandler) listEnterpriseOrg(ctx context.Context, config *code.GitHubSetting) (*code.ListGitHubEnterpriseOrgResponse, error) {
Putの方は、Enterprise内のOrgのリストを取得した結果をGitHubEnterpriseOrgエンティティにデータを登録するために呼び出しています。
Deleteの方は、すでに登録されているOrgの中で今回見つからなかったものを削除するために呼び出しています。

ただ、現状GitHubEnterpriseOrgの用途がないためPut処理Delete処理共に削除して用途が出てきたタイミングで追加しようと思います。

2022-08-24 13:43 UTC, iiiidaaa commented on src/dependency/crypto.go
> +		return []byte("")
GitHubSettingにPersonalAccessTokenが設定されていない場合に、空文字を返すようになっています。
ただPersonalAccessTokenが存在しない場合にはそもそもdecrypt処理が必要ないため、ご指摘の箇所はエラーにしてPersonalAccessTokenが空の場合にはdecrypt処理を行わないように修正します。

2022-08-24 13:48 UTC, iiiidaaa commented on src/dependency/handler.go
> +	if repo == nil {
repoがnilになるケースが想定されないため、errorを消すよう修正します。

2022-08-25 02:12 UTC, hnts commented on src/dependency/grpc_client.go
> +package main
> なので、共通化するならば全てのデータソースに適応できる形にすべきだと考えましたがいかがでしょうか？

理想的にはこれが良いと思います。ただそうするとスキャナー系の重複箇所をきれいにするという別タスクにしたほうがよさそうですね。

なので、ここはまずはこのリポジトリの範囲の中で重複を減らしておこうと思っていました。
ただ、モジュールが別ということを忘れておりました

この議論を進める前に確認なのですが、moduleを新たに追加することは想定内でしょうか？👀
moduleは増やさないという方針があると思うのですが、その方針との兼ね合いが気になりました

@mmmknt さんの意見も聞いてみたいです

2022-08-25 02:24 UTC, mmmknt commented on src/dependency/grpc_client.go
> +package main
構成はできるだけリポジトリ間で揃えた方が良いと思うので、このリポジトリの中だけで共通化するのは避けた方が良いかなと思います。
また、clientを共通化する場合でも、特にmoduleを別に切らなくてもいいかなと思っています。例えば、core/pkg/clientパッケージを切って、その下に呼び出し用のclientの実装を追加する、とか。
個別にモジュールを切る必要って何かあるんでしたっけ？

2022-08-25 02:36 UTC, hnts commented on src/dependency/grpc_client.go
> +package main
@mmmknt のコメント見ましたが、少し議論が複雑になっているっぽいですね:eyes:

僕の意見 -> 今回のリポジトリだけでも重複を減らして、全リポジトリの対応は後ほどやる
安里さん -> 重複を減らすなら全リポジトリを対応した方が良い(今やるかは別かな？)、coreなどにつくる
飯田さん -> 重複を減らすなら全リポジトリを対応した方が良い、もし今回のリポジトリだけやる場合はmoduleを作成しないでやる方法がわからない

こんな感じのようですね
確かにやるのであれば、飯田さんや安里さんが言うように全リポジトリ用のpkgをcoreなどに作る方が良さそうに思えました
https://github.com/ca-risken/core/blob/99d976980d0f85fd58be4f87e71aa5395680ce7c/pkg/server/server.go#L170

↑既にcoreにあるのでをpkg/clientみたいに切り分けて、スキャナー系は使うといいかもしれないですね

2022-08-26 14:15 UTC, iiiidaaa commented on src/dependency/Makefile
> +.PHONY: all run
ご指摘の通り、削除しました。

2022-08-26 14:19 UTC, iiiidaaa commented on src/dependency/crypto.go
> +		return []byte("")
復号対象の暗号文がaesのブロックサイズ未満の場合はエラーにするように修正しました。
また、PersonalAccessTokenが存在しない場合には、Decrypt処理を実施しないよう修正しました。
https://github.com/ca-risken/code/blob/b22005213ebe2d78df08d525577004f76f8aec86/src/dependency/handler.go#L177

2022-08-26 14:19 UTC, iiiidaaa commented on src/dependency/sqs.go
> +	Debug string `default:"false"`
SqsConfingに設定されていたタグを消去しました。

2022-08-26 14:20 UTC, iiiidaaa commented on src/dependency/main.go
> +		ServiceName:  fmt.Sprintf("%s.%s", nameSpace, serviceName),
ご指摘の通り、`getFullServiceName()`を使用するように修正しました。

2022-08-26 14:21 UTC, iiiidaaa commented on src/dependency/handler.go
> +	gitHubSetting.PersonalAccessToken = token // Set the plaintext so that the value is still decipherable next processes.
getGitHubSetting内でPersonalAccessTokenを差し替えるように修正しました。
https://github.com/ca-risken/code/blob/b22005213ebe2d78df08d525577004f76f8aec86/src/dependency/handler.go#L180

2022-08-26 14:22 UTC, iiiidaaa commented on src/dependency/handler.go
> +	if repo == nil {
skipScanの戻り値からerrorを消去しました。

2022-08-26 15:01 UTC, iiiidaaa commented on src/dependency/handler.go
> +func (s *sqsHandler) listEnterpriseOrg(ctx context.Context, config *code.GitHubSetting) (*code.ListGitHubEnterpriseOrgResponse, error) {
listEnterpriseOrgからPut,DeleteGitHubEnterpriseOrgの処理を消去しました。
また、GitHubEnterpriseOrgエンティティの情報を使わずに、`riskenGitHubClient.ListGitHubEnterpriseOrg`の戻り値をそのままOrgの一覧として使用するように修正したため本関数の戻り値も修正しています。

2022-08-26 15:04 UTC, iiiidaaa commented on src/dependency/finding.go
> +			if severity != "UNKNOWN" {
ご指摘の通りSeverityとScoreを対応させるmapを作成し、Vulnerabilityのループの中でScoreの値が高い時だけ更新するように修正しました。

2022-08-26 15:10 UTC, iiiidaaa commented on src/dependency/grpc_client.go
> +package main
コードの調査を行なった結果、以下のfunctionは`*grpc.ClientConn`を用意しておけば、エラー処理を行わずにprotoの自動生成されたfunctionを使用できることがわかりました。
```
func newFindingClient(svcAddr string) finding.FindingServiceClient
func newAlertClient(svcAddr string) alert.AlertServiceClient
func newCodeClient(svcAddr string) code.CodeServiceClient
```
そのため`func getGRPCConn(ctx context.Context, addr string) (*grpc.ClientConn, error)`のみ残し、newHandler側で`*grpc.ClientConn`を生成するように修正しました。
https://github.com/ca-risken/code/blob/61f1d81f98879c3e1a02fb5b2f1635c9ef45cd21/src/dependency/handler.go#L41

`func getGRPCConn(ctx context.Context, addr string) (*grpc.ClientConn, error)`に関しては共通化は行いません。

2022-08-26 15:10 UTC, iiiidaaa commented on src/dependency/finding.go
> +func makeFindings(msg *message.CodeQueueMessage, report *trivytypes.Report) ([]*finding.FindingBatchForUpsert, error) {
テストを作成しました。

2022-08-26 15:10 UTC, iiiidaaa commented on src/dependency/finding.go
> +func getScore(vulnerabilities []trivytypes.DetectedVulnerability) float32 {
テストを作成しました。

2022-08-26 16:01 UTC, iiiidaaa commented on src/dependency/dependency.go
> +		appLogger.Errorf(ctx, "Failed to execute trivy. error: %+v, stderr: %v", err, stderr.String())
cmd.Run実行時に発生したエラーは、ロギングせずに呼び出し側で処理できるよう修正します。
https://github.com/ca-risken/code/blob/ebf4d0c987c5f8f2e45badd280f9d5c95e03f9e9/src/dependency/dependency.go#L84

2022-08-26 16:02 UTC, iiiidaaa commented on src/dependency/sqs.go
> +package main
一旦、共通化しないこととしました。
ただし、ここに限らず共通化の問題は残っているためIssueを作成して検討していく予定です。

2022-08-26 16:04 UTC, iiiidaaa commented on Makefile
> +TARGETS = gitleaks dependency
他のコマンドと同様の方法でdependencyに対しても実行できるよう修正しました。

2022-08-26 16:04 UTC, iiiidaaa commented on src/dependency/Dockerfile
> +FROM public.ecr.aws/risken/code/dependency-base:v0.31.2
dependency-baseのバージョンをv0.0.1に変更しました。
https://github.com/ca-risken/code/blob/ebf4d0c987c5f8f2e45badd280f9d5c95e03f9e9/src/dependency/Dockerfile#L12

2022-08-26 16:09 UTC, iiiidaaa commented on src/dependency/Dockerfile
> +ENV DEBUG= \
以下の不要な環境変数を削除しました。
```
    AWS_SVC_ADDR
    SEPERATE_SCAN_DAYS
    DEPENDENCY_SCAN_THREADS
    SCAN_ON_MEMORY
```
また、以下の環境変数がAppConfigで設定されている値と一致していないため修正しました。
`FINDING_SVC_ADDR`,`ALERT_SVC_ADDR` => `CORE_SVC_ADDR`に修正
`   CODE_SVC_ADDR` => `DATA_SOURCE_API_SVC_ADDR`に修正

2022-08-26 16:14 UTC, iiiidaaa commented on src/dependency/grpc_client.go
> +		appLogger.Fatalf(ctx, "Faild to get GRPC connection: err=%+v", err)
*grpc.ClientConnをあらかじめ用意することで、protoファイルから自動生成されたコードを使用できることを確認したため、`newFindingClient`,`newAlertClient`,`newCodeClient`を削除しました。
`getGRPCConn`はhandlerに移動しています。
https://github.com/ca-risken/code/blob/ebf4d0c987c5f8f2e45badd280f9d5c95e03f9e9/src/dependency/handler.go#L33
また、この関数のエラー処理は以下で行っています。
https://github.com/ca-risken/code/blob/ebf4d0c987c5f8f2e45badd280f9d5c95e03f9e9/src/dependency/handler.go#L54

2022-08-26 16:15 UTC, iiiidaaa commented on src/dependency/dependency.go
> +	bytes, err := ioutil.ReadFile(fileName)
os.ReadFileを使用するように修正しました。
https://github.com/ca-risken/code/blob/ebf4d0c987c5f8f2e45badd280f9d5c95e03f9e9/src/dependency/dependency.go#L61

2022-08-26 16:17 UTC, iiiidaaa commented on src/dependency/dependency.go
> +	bytes, err := readAndDeleteFile(filePath)
テストを作成するにあたり、処理の内容が変わっていますが、削除系の処理が行われるように修正しました。
https://github.com/ca-risken/code/blob/ebf4d0c987c5f8f2e45badd280f9d5c95e03f9e9/src/dependency/dependency.go#L55

2022-08-26 16:23 UTC, iiiidaaa commented on src/dependency/dependency.go
> +func (d *dependencyClient) scan(ctx context.Context, repo *github.Repository, token string) (*trivytypes.Report, error) {
テストを作成しました。
テスト作成にあたり、dependencyの処理を変更しています。
`getResult(ctx context.Context, repo *github.Repository, token, filePath string) (*trivytypes.Report, error)`
存在していた`func scan`はスキャン実行(エラーのみ戻り値)に変更し、`getResult()`でファイルの読み込みとjson Unmarshalを実行するように修正しています。

2022-08-26 16:29 UTC, iiiidaaa commented on src/dependency/dependency.go
> +	cmd := exec.CommandContext(ctx, trivyPath, "repository", "--security-checks", "vuln", "--output", filePath, "--format", "json", *repo.CloneURL)
スキャンエラー時にもファイルが出力される場合があるため、エラー時にもファイルを削除するように修正しました。
https://github.com/ca-risken/code/blob/ebf4d0c987c5f8f2e45badd280f9d5c95e03f9e9/src/dependency/dependency.go#L55

2022-08-29 04:08 UTC, hnts requested changes

2022-08-29 04:08 UTC, hnts commented on src/dependency/dependency.go
> +func (t *trivyClient) scan(ctx context.Context, repo *github.Repository, token string, filePath string) error {
github.Repositoryを引数で受け取る必要はなく、urlで十分そうです

また、filePathという名前から使われ方が想像しにくいのでoutputPathでいかがでしょうか

2022-08-29 04:08 UTC, hnts commented on src/dependency/dependency.go
> +		return fmt.Errorf("execute trivy: err: %w", err)
trivyのエラーログのみを返却するのみで大丈夫そうでしょうか？
エラーが起きた時に追えるようにwrapしたほうがよさそうです

2022-08-29 09:37 UTC, mmmknt approved these changes
LGTM

2022-08-29 10:59 UTC, iiiidaaa commented on src/dependency/dependency.go
> +		return fmt.Errorf("execute trivy: err: %w", err)
独自エラーを作成し、stderrをhandler側で出力するように修正しました。
エラー時にDependencySettingに登録するエラー詳細には、stderrは含めないようにしています。
https://github.com/ca-risken/code/blob/7dce4dff3c8edd3b9606c0dcf12711d7c07129e5/src/dependency/dependency.go#L97
https://github.com/ca-risken/code/blob/7dce4dff3c8edd3b9606c0dcf12711d7c07129e5/src/dependency/handler.go#L119

2022-08-29 11:01 UTC, iiiidaaa commented on src/dependency/dependency.go
> +func (t *trivyClient) scan(ctx context.Context, repo *github.Repository, token string, filePath string) error {
scanの呼び出し元でもurl以外を使用していなかったため、handlerからcloneURLを引数として与えるように修正しました。
https://github.com/ca-risken/code/blob/7dce4dff3c8edd3b9606c0dcf12711d7c07129e5/src/dependency/handler.go#L117

また、ご指摘の通りfilePathをoutputPathに変更しています。

2022-08-29 11:01 UTC, iiiidaaa commented on src/dependency/dependency.go
> +func newtrivyClient(trivyPath string, exec exec.Interface) trivyScanner {
`newtrivyClient ` -> `newTrivyClient `に修正しました。

2022-08-29 11:49 UTC, iiiidaaa commented on src/dependency/finding.go
> +	SCORE_UNKNOWN     = float32(0.6)
trivy-dbに登録されている脆弱性のSeverityがUnknownの場合に、Score 0.6のSCORE_UNKNOWNを使っています。
VulnerabilityのSeverityは脆弱性情報の取得元ベンダかNVDのスコア/Severityによって、決定されますが脆弱性などによってスコア/Severityが付与されていないものを見つけました。

結果からRISKENでのスコアを算定できないため、以下の理由により0.6としました。
- 基本的にアラートはスコア0.8以上のFIndingが登録された場合に通知されるよう設定されていること
- HIGH,CRITICALの明らかにSeverityが高いもののみを通知させるため

ご質問の意図としてはスコアを0.6にした理由をコメントなどで追記しておくべき、もしくはスコア0.6でなく別のスコアを設定した方がいいという感じでしょうか？

2022-08-30 02:02 UTC, hnts commented on src/dependency/dependency.go
> +		return fmt.Errorf("execute trivy: err: %w", err)
あ、独自の型はいらなそうですかね？

単純に以下のように、trivy以外のエラーの情報を付加しておいたほうが追いやすいかなと思いました
```
fmt.Errorf("failed to execute trivy: err=%w, cloneURL=%s", err, cloneURL)
```

みたいな感じですね
エラー時に現時点の情報で追えるのであれば大丈夫です

一点だけですが、エラーメッセージが気になりました
failed to ~ で揃えたほうが一貫性があるかもしれません

2022-08-30 02:08 UTC, hnts commented on src/dependency/finding.go
> +	SCORE_UNKNOWN     = float32(0.6)
> ご質問の意図としてはスコアを0.6にした理由をコメントなどで追記しておくべき、もしくはスコア0.6でなく別のスコアを設定した方がいいという感じでしょうか？

これらがチームで合意されたロジック、妥当なロジックなのかを確認したかったです
LOWよりもUNKNOWNが高くなる理由が気になりましたが、これはチームとの相談の方が良いかもしれません

別として理由をコメント、ドキュメントに書いた方がいいと思います！

2022-09-01 09:28 UTC, iiiidaaa commented on src/dependency/finding.go
> +	SCORE_UNKNOWN     = float32(0.6)
スコアに関して、一旦一律で引き下げました。
こちらに関してはIssueを作成しており、そちらでスコアの方針が決まった後に修正する予定です。

また、trivyの結果から脆弱性(VulnerabilityID)ごとにFindingを作成するように修正しています。

2022-09-01 09:33 UTC, iiiidaaa commented on src/dependency/dependency.go
> +		return fmt.Errorf("execute trivy: err: %w", err)
ご指摘の通りにエラーを変更しました。(独自の方は削除しています)
```go
fmt.Errorf("failed to execute trivy: err=%w, cloneURL=%s", err, cloneURL)
```
また、それに合わせてhandler側でエラーを受け取った際の挙動を変更しました。
(独自エラーのチェック削除,リポジトリのURLはもともとログに吐いていただけでしたが、今回の変更でユーザーにまで伝わるようになった)
https://github.com/ca-risken/code/blob/7f2d8cfddcb096dc33a44dc9f0ac87664aa31d5e/src/dependency/handler.go#L119

2022-09-06 05:55 UTC, hnts approved these changes

2022-09-06 05:55 UTC, hnts commented
LGTM

2022-09-06 05:58 UTC, merged