delete githubURL and author(adhoc)
ca-risken/code pull request #163
Opened 2024-03-18 09:15 UTC by senk8

2024-03-18 10:08 UTC, gassara-kys approved these changes
LGTM

2024-03-18 10:09 UTC, gassara-kys requested changes
すいません、このテンプレートを使っている呼ぼだしもとの実装も修正が必要な認識です

2024-03-21 05:49 UTC, gassara-kys approved these changes
LGTM

2024-03-21 05:50 UTC, iiiidaaa approved these changes
LGTM

2024-03-21 07:07 UTC, senk8 commented
masterの取り込み後にマージ

2024-03-21 07:18 UTC, merged